# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ballot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62\x61llot.proto\"O\n\x1dPlaintextBallotSelectionProto\x12\x0c\n\x04vote\x18\x01 \x02(\x08\x12 \n\x18is_placeholder_selection\x18\x02 \x02(\x08\"p\n\x1bPlaintextBallotContestProto\x12\x16\n\x0enum_selections\x18\x01 \x02(\x05\x12\x39\n\x11\x62\x61llot_selections\x18\x02 \x03(\x0b\x32\x1e.PlaintextBallotSelectionProto\"n\n\x14PlaintextBallotProto\x12\x10\n\x08style_id\x18\x01 \x02(\t\x12\x14\n\x0cnum_contests\x18\x02 \x02(\x05\x12.\n\x08\x63ontests\x18\x03 \x03(\x0b\x32\x1c.PlaintextBallotContestProto\"_\n\x15\x43iphertextBallotProto\x12\x10\n\x08style_id\x18\x01 \x02(\t\x12\x11\n\tcode_seed\x18\x02 \x02(\x0c\x12\x0c\n\x04\x63ode\x18\x03 \x02(\x0c\x12\x13\n\x0b\x63rypto_hash\x18\x04 \x02(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ballot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAINTEXTBALLOTSELECTIONPROTO._serialized_start=16
  _PLAINTEXTBALLOTSELECTIONPROTO._serialized_end=95
  _PLAINTEXTBALLOTCONTESTPROTO._serialized_start=97
  _PLAINTEXTBALLOTCONTESTPROTO._serialized_end=209
  _PLAINTEXTBALLOTPROTO._serialized_start=211
  _PLAINTEXTBALLOTPROTO._serialized_end=321
  _CIPHERTEXTBALLOTPROTO._serialized_start=323
  _CIPHERTEXTBALLOTPROTO._serialized_end=418
# @@protoc_insertion_point(module_scope)
