/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ballot.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ballot.pb-c.h"
void   plaintext_ballot_selection_proto__init
                     (PlaintextBallotSelectionProto         *message)
{
  static const PlaintextBallotSelectionProto init_value = PLAINTEXT_BALLOT_SELECTION_PROTO__INIT;
  *message = init_value;
}
size_t plaintext_ballot_selection_proto__get_packed_size
                     (const PlaintextBallotSelectionProto *message)
{
  assert(message->base.descriptor == &plaintext_ballot_selection_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plaintext_ballot_selection_proto__pack
                     (const PlaintextBallotSelectionProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plaintext_ballot_selection_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plaintext_ballot_selection_proto__pack_to_buffer
                     (const PlaintextBallotSelectionProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plaintext_ballot_selection_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlaintextBallotSelectionProto *
       plaintext_ballot_selection_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlaintextBallotSelectionProto *)
     protobuf_c_message_unpack (&plaintext_ballot_selection_proto__descriptor,
                                allocator, len, data);
}
void   plaintext_ballot_selection_proto__free_unpacked
                     (PlaintextBallotSelectionProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plaintext_ballot_selection_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plaintext_ballot_contest_proto__init
                     (PlaintextBallotContestProto         *message)
{
  static const PlaintextBallotContestProto init_value = PLAINTEXT_BALLOT_CONTEST_PROTO__INIT;
  *message = init_value;
}
size_t plaintext_ballot_contest_proto__get_packed_size
                     (const PlaintextBallotContestProto *message)
{
  assert(message->base.descriptor == &plaintext_ballot_contest_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plaintext_ballot_contest_proto__pack
                     (const PlaintextBallotContestProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plaintext_ballot_contest_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plaintext_ballot_contest_proto__pack_to_buffer
                     (const PlaintextBallotContestProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plaintext_ballot_contest_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlaintextBallotContestProto *
       plaintext_ballot_contest_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlaintextBallotContestProto *)
     protobuf_c_message_unpack (&plaintext_ballot_contest_proto__descriptor,
                                allocator, len, data);
}
void   plaintext_ballot_contest_proto__free_unpacked
                     (PlaintextBallotContestProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plaintext_ballot_contest_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   plaintext_ballot_proto__init
                     (PlaintextBallotProto         *message)
{
  static const PlaintextBallotProto init_value = PLAINTEXT_BALLOT_PROTO__INIT;
  *message = init_value;
}
size_t plaintext_ballot_proto__get_packed_size
                     (const PlaintextBallotProto *message)
{
  assert(message->base.descriptor == &plaintext_ballot_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t plaintext_ballot_proto__pack
                     (const PlaintextBallotProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &plaintext_ballot_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t plaintext_ballot_proto__pack_to_buffer
                     (const PlaintextBallotProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &plaintext_ballot_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PlaintextBallotProto *
       plaintext_ballot_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PlaintextBallotProto *)
     protobuf_c_message_unpack (&plaintext_ballot_proto__descriptor,
                                allocator, len, data);
}
void   plaintext_ballot_proto__free_unpacked
                     (PlaintextBallotProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &plaintext_ballot_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciphertext_ballot_proto__init
                     (CiphertextBallotProto         *message)
{
  static const CiphertextBallotProto init_value = CIPHERTEXT_BALLOT_PROTO__INIT;
  *message = init_value;
}
size_t ciphertext_ballot_proto__get_packed_size
                     (const CiphertextBallotProto *message)
{
  assert(message->base.descriptor == &ciphertext_ballot_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciphertext_ballot_proto__pack
                     (const CiphertextBallotProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciphertext_ballot_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciphertext_ballot_proto__pack_to_buffer
                     (const CiphertextBallotProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciphertext_ballot_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CiphertextBallotProto *
       ciphertext_ballot_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CiphertextBallotProto *)
     protobuf_c_message_unpack (&ciphertext_ballot_proto__descriptor,
                                allocator, len, data);
}
void   ciphertext_ballot_proto__free_unpacked
                     (CiphertextBallotProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciphertext_ballot_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor plaintext_ballot_selection_proto__field_descriptors[2] =
{
  {
    "vote",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PlaintextBallotSelectionProto, vote),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_placeholder_selection",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(PlaintextBallotSelectionProto, is_placeholder_selection),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plaintext_ballot_selection_proto__field_indices_by_name[] = {
  1,   /* field[1] = is_placeholder_selection */
  0,   /* field[0] = vote */
};
static const ProtobufCIntRange plaintext_ballot_selection_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plaintext_ballot_selection_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlaintextBallotSelectionProto",
  "PlaintextBallotSelectionProto",
  "PlaintextBallotSelectionProto",
  "",
  sizeof(PlaintextBallotSelectionProto),
  2,
  plaintext_ballot_selection_proto__field_descriptors,
  plaintext_ballot_selection_proto__field_indices_by_name,
  1,  plaintext_ballot_selection_proto__number_ranges,
  (ProtobufCMessageInit) plaintext_ballot_selection_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plaintext_ballot_contest_proto__field_descriptors[2] =
{
  {
    "num_selections",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlaintextBallotContestProto, num_selections),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ballot_selections",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PlaintextBallotContestProto, n_ballot_selections),
    offsetof(PlaintextBallotContestProto, ballot_selections),
    &plaintext_ballot_selection_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plaintext_ballot_contest_proto__field_indices_by_name[] = {
  1,   /* field[1] = ballot_selections */
  0,   /* field[0] = num_selections */
};
static const ProtobufCIntRange plaintext_ballot_contest_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor plaintext_ballot_contest_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlaintextBallotContestProto",
  "PlaintextBallotContestProto",
  "PlaintextBallotContestProto",
  "",
  sizeof(PlaintextBallotContestProto),
  2,
  plaintext_ballot_contest_proto__field_descriptors,
  plaintext_ballot_contest_proto__field_indices_by_name,
  1,  plaintext_ballot_contest_proto__number_ranges,
  (ProtobufCMessageInit) plaintext_ballot_contest_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor plaintext_ballot_proto__field_descriptors[3] =
{
  {
    "style_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PlaintextBallotProto, style_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_contests",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PlaintextBallotProto, num_contests),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contests",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PlaintextBallotProto, n_contests),
    offsetof(PlaintextBallotProto, contests),
    &plaintext_ballot_contest_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned plaintext_ballot_proto__field_indices_by_name[] = {
  2,   /* field[2] = contests */
  1,   /* field[1] = num_contests */
  0,   /* field[0] = style_id */
};
static const ProtobufCIntRange plaintext_ballot_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor plaintext_ballot_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PlaintextBallotProto",
  "PlaintextBallotProto",
  "PlaintextBallotProto",
  "",
  sizeof(PlaintextBallotProto),
  3,
  plaintext_ballot_proto__field_descriptors,
  plaintext_ballot_proto__field_indices_by_name,
  1,  plaintext_ballot_proto__number_ranges,
  (ProtobufCMessageInit) plaintext_ballot_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciphertext_ballot_proto__field_descriptors[4] =
{
  {
    "style_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CiphertextBallotProto, style_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code_seed",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextBallotProto, code_seed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextBallotProto, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crypto_hash",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextBallotProto, crypto_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciphertext_ballot_proto__field_indices_by_name[] = {
  2,   /* field[2] = code */
  1,   /* field[1] = code_seed */
  3,   /* field[3] = crypto_hash */
  0,   /* field[0] = style_id */
};
static const ProtobufCIntRange ciphertext_ballot_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ciphertext_ballot_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CiphertextBallotProto",
  "CiphertextBallotProto",
  "CiphertextBallotProto",
  "",
  sizeof(CiphertextBallotProto),
  4,
  ciphertext_ballot_proto__field_descriptors,
  ciphertext_ballot_proto__field_indices_by_name,
  1,  ciphertext_ballot_proto__number_ranges,
  (ProtobufCMessageInit) ciphertext_ballot_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
