/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tally.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tally.pb-c.h"
void   ciphertext_tally_selection_proto__init
                     (CiphertextTallySelectionProto         *message)
{
  static const CiphertextTallySelectionProto init_value = CIPHERTEXT_TALLY_SELECTION_PROTO__INIT;
  *message = init_value;
}
size_t ciphertext_tally_selection_proto__get_packed_size
                     (const CiphertextTallySelectionProto *message)
{
  assert(message->base.descriptor == &ciphertext_tally_selection_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciphertext_tally_selection_proto__pack
                     (const CiphertextTallySelectionProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciphertext_tally_selection_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciphertext_tally_selection_proto__pack_to_buffer
                     (const CiphertextTallySelectionProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciphertext_tally_selection_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CiphertextTallySelectionProto *
       ciphertext_tally_selection_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CiphertextTallySelectionProto *)
     protobuf_c_message_unpack (&ciphertext_tally_selection_proto__descriptor,
                                allocator, len, data);
}
void   ciphertext_tally_selection_proto__free_unpacked
                     (CiphertextTallySelectionProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciphertext_tally_selection_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciphertext_tally_contest_proto__init
                     (CiphertextTallyContestProto         *message)
{
  static const CiphertextTallyContestProto init_value = CIPHERTEXT_TALLY_CONTEST_PROTO__INIT;
  *message = init_value;
}
size_t ciphertext_tally_contest_proto__get_packed_size
                     (const CiphertextTallyContestProto *message)
{
  assert(message->base.descriptor == &ciphertext_tally_contest_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciphertext_tally_contest_proto__pack
                     (const CiphertextTallyContestProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciphertext_tally_contest_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciphertext_tally_contest_proto__pack_to_buffer
                     (const CiphertextTallyContestProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciphertext_tally_contest_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CiphertextTallyContestProto *
       ciphertext_tally_contest_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CiphertextTallyContestProto *)
     protobuf_c_message_unpack (&ciphertext_tally_contest_proto__descriptor,
                                allocator, len, data);
}
void   ciphertext_tally_contest_proto__free_unpacked
                     (CiphertextTallyContestProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciphertext_tally_contest_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciphertext_tally_proto__init
                     (CiphertextTallyProto         *message)
{
  static const CiphertextTallyProto init_value = CIPHERTEXT_TALLY_PROTO__INIT;
  *message = init_value;
}
size_t ciphertext_tally_proto__get_packed_size
                     (const CiphertextTallyProto *message)
{
  assert(message->base.descriptor == &ciphertext_tally_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciphertext_tally_proto__pack
                     (const CiphertextTallyProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciphertext_tally_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciphertext_tally_proto__pack_to_buffer
                     (const CiphertextTallyProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciphertext_tally_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CiphertextTallyProto *
       ciphertext_tally_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CiphertextTallyProto *)
     protobuf_c_message_unpack (&ciphertext_tally_proto__descriptor,
                                allocator, len, data);
}
void   ciphertext_tally_proto__free_unpacked
                     (CiphertextTallyProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciphertext_tally_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciphertext_decryption_selection_proto__init
                     (CiphertextDecryptionSelectionProto         *message)
{
  static const CiphertextDecryptionSelectionProto init_value = CIPHERTEXT_DECRYPTION_SELECTION_PROTO__INIT;
  *message = init_value;
}
size_t ciphertext_decryption_selection_proto__get_packed_size
                     (const CiphertextDecryptionSelectionProto *message)
{
  assert(message->base.descriptor == &ciphertext_decryption_selection_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciphertext_decryption_selection_proto__pack
                     (const CiphertextDecryptionSelectionProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciphertext_decryption_selection_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciphertext_decryption_selection_proto__pack_to_buffer
                     (const CiphertextDecryptionSelectionProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciphertext_decryption_selection_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CiphertextDecryptionSelectionProto *
       ciphertext_decryption_selection_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CiphertextDecryptionSelectionProto *)
     protobuf_c_message_unpack (&ciphertext_decryption_selection_proto__descriptor,
                                allocator, len, data);
}
void   ciphertext_decryption_selection_proto__free_unpacked
                     (CiphertextDecryptionSelectionProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciphertext_decryption_selection_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ciphertext_decryption_contest_proto__init
                     (CiphertextDecryptionContestProto         *message)
{
  static const CiphertextDecryptionContestProto init_value = CIPHERTEXT_DECRYPTION_CONTEST_PROTO__INIT;
  *message = init_value;
}
size_t ciphertext_decryption_contest_proto__get_packed_size
                     (const CiphertextDecryptionContestProto *message)
{
  assert(message->base.descriptor == &ciphertext_decryption_contest_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ciphertext_decryption_contest_proto__pack
                     (const CiphertextDecryptionContestProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ciphertext_decryption_contest_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ciphertext_decryption_contest_proto__pack_to_buffer
                     (const CiphertextDecryptionContestProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ciphertext_decryption_contest_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CiphertextDecryptionContestProto *
       ciphertext_decryption_contest_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CiphertextDecryptionContestProto *)
     protobuf_c_message_unpack (&ciphertext_decryption_contest_proto__descriptor,
                                allocator, len, data);
}
void   ciphertext_decryption_contest_proto__free_unpacked
                     (CiphertextDecryptionContestProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ciphertext_decryption_contest_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   decryption_share_proto__init
                     (DecryptionShareProto         *message)
{
  static const DecryptionShareProto init_value = DECRYPTION_SHARE_PROTO__INIT;
  *message = init_value;
}
size_t decryption_share_proto__get_packed_size
                     (const DecryptionShareProto *message)
{
  assert(message->base.descriptor == &decryption_share_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t decryption_share_proto__pack
                     (const DecryptionShareProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &decryption_share_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t decryption_share_proto__pack_to_buffer
                     (const DecryptionShareProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &decryption_share_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DecryptionShareProto *
       decryption_share_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DecryptionShareProto *)
     protobuf_c_message_unpack (&decryption_share_proto__descriptor,
                                allocator, len, data);
}
void   decryption_share_proto__free_unpacked
                     (DecryptionShareProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &decryption_share_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ciphertext_tally_selection_proto__field_descriptors[3] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallySelectionProto, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ciphertext_pad",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallySelectionProto, ciphertext_pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ciphertext_data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallySelectionProto, ciphertext_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciphertext_tally_selection_proto__field_indices_by_name[] = {
  2,   /* field[2] = ciphertext_data */
  1,   /* field[1] = ciphertext_pad */
  0,   /* field[0] = object_id */
};
static const ProtobufCIntRange ciphertext_tally_selection_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ciphertext_tally_selection_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CiphertextTallySelectionProto",
  "CiphertextTallySelectionProto",
  "CiphertextTallySelectionProto",
  "",
  sizeof(CiphertextTallySelectionProto),
  3,
  ciphertext_tally_selection_proto__field_descriptors,
  ciphertext_tally_selection_proto__field_indices_by_name,
  1,  ciphertext_tally_selection_proto__number_ranges,
  (ProtobufCMessageInit) ciphertext_tally_selection_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciphertext_tally_contest_proto__field_descriptors[5] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallyContestProto, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_order",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallyContestProto, sequence_order),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description_hash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallyContestProto, description_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_selections",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallyContestProto, num_selections),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "selections",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CiphertextTallyContestProto, n_selections),
    offsetof(CiphertextTallyContestProto, selections),
    &ciphertext_tally_selection_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciphertext_tally_contest_proto__field_indices_by_name[] = {
  2,   /* field[2] = description_hash */
  3,   /* field[3] = num_selections */
  0,   /* field[0] = object_id */
  4,   /* field[4] = selections */
  1,   /* field[1] = sequence_order */
};
static const ProtobufCIntRange ciphertext_tally_contest_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ciphertext_tally_contest_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CiphertextTallyContestProto",
  "CiphertextTallyContestProto",
  "CiphertextTallyContestProto",
  "",
  sizeof(CiphertextTallyContestProto),
  5,
  ciphertext_tally_contest_proto__field_descriptors,
  ciphertext_tally_contest_proto__field_indices_by_name,
  1,  ciphertext_tally_contest_proto__number_ranges,
  (ProtobufCMessageInit) ciphertext_tally_contest_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciphertext_tally_proto__field_descriptors[4] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallyProto, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallyProto, base_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_contest",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CiphertextTallyProto, num_contest),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contests",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CiphertextTallyProto, n_contests),
    offsetof(CiphertextTallyProto, contests),
    &ciphertext_tally_contest_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciphertext_tally_proto__field_indices_by_name[] = {
  1,   /* field[1] = base_hash */
  3,   /* field[3] = contests */
  2,   /* field[2] = num_contest */
  0,   /* field[0] = object_id */
};
static const ProtobufCIntRange ciphertext_tally_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ciphertext_tally_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CiphertextTallyProto",
  "CiphertextTallyProto",
  "CiphertextTallyProto",
  "",
  sizeof(CiphertextTallyProto),
  4,
  ciphertext_tally_proto__field_descriptors,
  ciphertext_tally_proto__field_indices_by_name,
  1,  ciphertext_tally_proto__number_ranges,
  (ProtobufCMessageInit) ciphertext_tally_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciphertext_decryption_selection_proto__field_descriptors[7] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionSelectionProto, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guardian_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionSelectionProto, guardian_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decryption",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionSelectionProto, decryption),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof_pad",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionSelectionProto, proof_pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof_data",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionSelectionProto, proof_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof_challenge",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionSelectionProto, proof_challenge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof_response",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionSelectionProto, proof_response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciphertext_decryption_selection_proto__field_indices_by_name[] = {
  2,   /* field[2] = decryption */
  1,   /* field[1] = guardian_id */
  0,   /* field[0] = object_id */
  5,   /* field[5] = proof_challenge */
  4,   /* field[4] = proof_data */
  3,   /* field[3] = proof_pad */
  6,   /* field[6] = proof_response */
};
static const ProtobufCIntRange ciphertext_decryption_selection_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ciphertext_decryption_selection_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CiphertextDecryptionSelectionProto",
  "CiphertextDecryptionSelectionProto",
  "CiphertextDecryptionSelectionProto",
  "",
  sizeof(CiphertextDecryptionSelectionProto),
  7,
  ciphertext_decryption_selection_proto__field_descriptors,
  ciphertext_decryption_selection_proto__field_indices_by_name,
  1,  ciphertext_decryption_selection_proto__number_ranges,
  (ProtobufCMessageInit) ciphertext_decryption_selection_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ciphertext_decryption_contest_proto__field_descriptors[5] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionContestProto, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guardian_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionContestProto, guardian_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description_hash",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionContestProto, description_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_selections",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CiphertextDecryptionContestProto, num_selections),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "selections",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(CiphertextDecryptionContestProto, n_selections),
    offsetof(CiphertextDecryptionContestProto, selections),
    &ciphertext_decryption_selection_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ciphertext_decryption_contest_proto__field_indices_by_name[] = {
  2,   /* field[2] = description_hash */
  1,   /* field[1] = guardian_id */
  3,   /* field[3] = num_selections */
  0,   /* field[0] = object_id */
  4,   /* field[4] = selections */
};
static const ProtobufCIntRange ciphertext_decryption_contest_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ciphertext_decryption_contest_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CiphertextDecryptionContestProto",
  "CiphertextDecryptionContestProto",
  "CiphertextDecryptionContestProto",
  "",
  sizeof(CiphertextDecryptionContestProto),
  5,
  ciphertext_decryption_contest_proto__field_descriptors,
  ciphertext_decryption_contest_proto__field_indices_by_name,
  1,  ciphertext_decryption_contest_proto__number_ranges,
  (ProtobufCMessageInit) ciphertext_decryption_contest_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor decryption_share_proto__field_descriptors[5] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DecryptionShareProto, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guardian_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DecryptionShareProto, guardian_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DecryptionShareProto, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_contests",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DecryptionShareProto, num_contests),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contests",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DecryptionShareProto, n_contests),
    offsetof(DecryptionShareProto, contests),
    &ciphertext_decryption_contest_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned decryption_share_proto__field_indices_by_name[] = {
  4,   /* field[4] = contests */
  1,   /* field[1] = guardian_id */
  3,   /* field[3] = num_contests */
  0,   /* field[0] = object_id */
  2,   /* field[2] = public_key */
};
static const ProtobufCIntRange decryption_share_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor decryption_share_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DecryptionShareProto",
  "DecryptionShareProto",
  "DecryptionShareProto",
  "",
  sizeof(DecryptionShareProto),
  5,
  decryption_share_proto__field_descriptors,
  decryption_share_proto__field_indices_by_name,
  1,  decryption_share_proto__number_ranges,
  (ProtobufCMessageInit) decryption_share_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
