/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: buff.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "buff.pb-c.h"
void   schnorr_proof_proto__init
                     (SchnorrProofProto         *message)
{
  static const SchnorrProofProto init_value = SCHNORR_PROOF_PROTO__INIT;
  *message = init_value;
}
size_t schnorr_proof_proto__get_packed_size
                     (const SchnorrProofProto *message)
{
  assert(message->base.descriptor == &schnorr_proof_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t schnorr_proof_proto__pack
                     (const SchnorrProofProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &schnorr_proof_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t schnorr_proof_proto__pack_to_buffer
                     (const SchnorrProofProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &schnorr_proof_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SchnorrProofProto *
       schnorr_proof_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SchnorrProofProto *)
     protobuf_c_message_unpack (&schnorr_proof_proto__descriptor,
                                allocator, len, data);
}
void   schnorr_proof_proto__free_unpacked
                     (SchnorrProofProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &schnorr_proof_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   coefficient_proto__init
                     (CoefficientProto         *message)
{
  static const CoefficientProto init_value = COEFFICIENT_PROTO__INIT;
  *message = init_value;
}
size_t coefficient_proto__get_packed_size
                     (const CoefficientProto *message)
{
  assert(message->base.descriptor == &coefficient_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t coefficient_proto__pack
                     (const CoefficientProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &coefficient_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t coefficient_proto__pack_to_buffer
                     (const CoefficientProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &coefficient_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CoefficientProto *
       coefficient_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CoefficientProto *)
     protobuf_c_message_unpack (&coefficient_proto__descriptor,
                                allocator, len, data);
}
void   coefficient_proto__free_unpacked
                     (CoefficientProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &coefficient_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   election_polynomial_proto__init
                     (ElectionPolynomialProto         *message)
{
  static const ElectionPolynomialProto init_value = ELECTION_POLYNOMIAL_PROTO__INIT;
  *message = init_value;
}
size_t election_polynomial_proto__get_packed_size
                     (const ElectionPolynomialProto *message)
{
  assert(message->base.descriptor == &election_polynomial_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t election_polynomial_proto__pack
                     (const ElectionPolynomialProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &election_polynomial_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t election_polynomial_proto__pack_to_buffer
                     (const ElectionPolynomialProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &election_polynomial_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ElectionPolynomialProto *
       election_polynomial_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ElectionPolynomialProto *)
     protobuf_c_message_unpack (&election_polynomial_proto__descriptor,
                                allocator, len, data);
}
void   election_polynomial_proto__free_unpacked
                     (ElectionPolynomialProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &election_polynomial_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   election_key_pair_proto__init
                     (ElectionKeyPairProto         *message)
{
  static const ElectionKeyPairProto init_value = ELECTION_KEY_PAIR_PROTO__INIT;
  *message = init_value;
}
size_t election_key_pair_proto__get_packed_size
                     (const ElectionKeyPairProto *message)
{
  assert(message->base.descriptor == &election_key_pair_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t election_key_pair_proto__pack
                     (const ElectionKeyPairProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &election_key_pair_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t election_key_pair_proto__pack_to_buffer
                     (const ElectionKeyPairProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &election_key_pair_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ElectionKeyPairProto *
       election_key_pair_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ElectionKeyPairProto *)
     protobuf_c_message_unpack (&election_key_pair_proto__descriptor,
                                allocator, len, data);
}
void   election_key_pair_proto__free_unpacked
                     (ElectionKeyPairProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &election_key_pair_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hashed_el_gamal_ciphertext_proto__init
                     (HashedElGamalCiphertextProto         *message)
{
  static const HashedElGamalCiphertextProto init_value = HASHED_EL_GAMAL_CIPHERTEXT_PROTO__INIT;
  *message = init_value;
}
size_t hashed_el_gamal_ciphertext_proto__get_packed_size
                     (const HashedElGamalCiphertextProto *message)
{
  assert(message->base.descriptor == &hashed_el_gamal_ciphertext_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hashed_el_gamal_ciphertext_proto__pack
                     (const HashedElGamalCiphertextProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hashed_el_gamal_ciphertext_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hashed_el_gamal_ciphertext_proto__pack_to_buffer
                     (const HashedElGamalCiphertextProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hashed_el_gamal_ciphertext_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HashedElGamalCiphertextProto *
       hashed_el_gamal_ciphertext_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HashedElGamalCiphertextProto *)
     protobuf_c_message_unpack (&hashed_el_gamal_ciphertext_proto__descriptor,
                                allocator, len, data);
}
void   hashed_el_gamal_ciphertext_proto__free_unpacked
                     (HashedElGamalCiphertextProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hashed_el_gamal_ciphertext_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   election_partial_key_pair_backup_proto__init
                     (ElectionPartialKeyPairBackupProto         *message)
{
  static const ElectionPartialKeyPairBackupProto init_value = ELECTION_PARTIAL_KEY_PAIR_BACKUP_PROTO__INIT;
  *message = init_value;
}
size_t election_partial_key_pair_backup_proto__get_packed_size
                     (const ElectionPartialKeyPairBackupProto *message)
{
  assert(message->base.descriptor == &election_partial_key_pair_backup_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t election_partial_key_pair_backup_proto__pack
                     (const ElectionPartialKeyPairBackupProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &election_partial_key_pair_backup_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t election_partial_key_pair_backup_proto__pack_to_buffer
                     (const ElectionPartialKeyPairBackupProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &election_partial_key_pair_backup_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ElectionPartialKeyPairBackupProto *
       election_partial_key_pair_backup_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ElectionPartialKeyPairBackupProto *)
     protobuf_c_message_unpack (&election_partial_key_pair_backup_proto__descriptor,
                                allocator, len, data);
}
void   election_partial_key_pair_backup_proto__free_unpacked
                     (ElectionPartialKeyPairBackupProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &election_partial_key_pair_backup_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   election_partial_key_verification_proto__init
                     (ElectionPartialKeyVerificationProto         *message)
{
  static const ElectionPartialKeyVerificationProto init_value = ELECTION_PARTIAL_KEY_VERIFICATION_PROTO__INIT;
  *message = init_value;
}
size_t election_partial_key_verification_proto__get_packed_size
                     (const ElectionPartialKeyVerificationProto *message)
{
  assert(message->base.descriptor == &election_partial_key_verification_proto__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t election_partial_key_verification_proto__pack
                     (const ElectionPartialKeyVerificationProto *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &election_partial_key_verification_proto__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t election_partial_key_verification_proto__pack_to_buffer
                     (const ElectionPartialKeyVerificationProto *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &election_partial_key_verification_proto__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ElectionPartialKeyVerificationProto *
       election_partial_key_verification_proto__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ElectionPartialKeyVerificationProto *)
     protobuf_c_message_unpack (&election_partial_key_verification_proto__descriptor,
                                allocator, len, data);
}
void   election_partial_key_verification_proto__free_unpacked
                     (ElectionPartialKeyVerificationProto *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &election_partial_key_verification_proto__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor schnorr_proof_proto__field_descriptors[4] =
{
  {
    "pubkey",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SchnorrProofProto, pubkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commitment",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SchnorrProofProto, commitment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SchnorrProofProto, challenge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(SchnorrProofProto, response),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned schnorr_proof_proto__field_indices_by_name[] = {
  2,   /* field[2] = challenge */
  1,   /* field[1] = commitment */
  0,   /* field[0] = pubkey */
  3,   /* field[3] = response */
};
static const ProtobufCIntRange schnorr_proof_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor schnorr_proof_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SchnorrProofProto",
  "SchnorrProofProto",
  "SchnorrProofProto",
  "",
  sizeof(SchnorrProofProto),
  4,
  schnorr_proof_proto__field_descriptors,
  schnorr_proof_proto__field_indices_by_name,
  1,  schnorr_proof_proto__number_ranges,
  (ProtobufCMessageInit) schnorr_proof_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor coefficient_proto__field_descriptors[3] =
{
  {
    "value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CoefficientProto, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commitment",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CoefficientProto, commitment),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CoefficientProto, proof),
    &schnorr_proof_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned coefficient_proto__field_indices_by_name[] = {
  1,   /* field[1] = commitment */
  2,   /* field[2] = proof */
  0,   /* field[0] = value */
};
static const ProtobufCIntRange coefficient_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor coefficient_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CoefficientProto",
  "CoefficientProto",
  "CoefficientProto",
  "",
  sizeof(CoefficientProto),
  3,
  coefficient_proto__field_descriptors,
  coefficient_proto__field_indices_by_name,
  1,  coefficient_proto__number_ranges,
  (ProtobufCMessageInit) coefficient_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor election_polynomial_proto__field_descriptors[2] =
{
  {
    "num_coefficients",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ElectionPolynomialProto, num_coefficients),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coefficients",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ElectionPolynomialProto, n_coefficients),
    offsetof(ElectionPolynomialProto, coefficients),
    &coefficient_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned election_polynomial_proto__field_indices_by_name[] = {
  1,   /* field[1] = coefficients */
  0,   /* field[0] = num_coefficients */
};
static const ProtobufCIntRange election_polynomial_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor election_polynomial_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ElectionPolynomialProto",
  "ElectionPolynomialProto",
  "ElectionPolynomialProto",
  "",
  sizeof(ElectionPolynomialProto),
  2,
  election_polynomial_proto__field_descriptors,
  election_polynomial_proto__field_indices_by_name,
  1,  election_polynomial_proto__number_ranges,
  (ProtobufCMessageInit) election_polynomial_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor election_key_pair_proto__field_descriptors[4] =
{
  {
    "guardian_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionKeyPairProto, guardian_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionKeyPairProto, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionKeyPairProto, private_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "polynomial",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ElectionKeyPairProto, polynomial),
    &election_polynomial_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned election_key_pair_proto__field_indices_by_name[] = {
  0,   /* field[0] = guardian_id */
  3,   /* field[3] = polynomial */
  2,   /* field[2] = private_key */
  1,   /* field[1] = public_key */
};
static const ProtobufCIntRange election_key_pair_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor election_key_pair_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ElectionKeyPairProto",
  "ElectionKeyPairProto",
  "ElectionKeyPairProto",
  "",
  sizeof(ElectionKeyPairProto),
  4,
  election_key_pair_proto__field_descriptors,
  election_key_pair_proto__field_indices_by_name,
  1,  election_key_pair_proto__number_ranges,
  (ProtobufCMessageInit) election_key_pair_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hashed_el_gamal_ciphertext_proto__field_descriptors[3] =
{
  {
    "pad",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HashedElGamalCiphertextProto, pad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HashedElGamalCiphertextProto, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HashedElGamalCiphertextProto, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hashed_el_gamal_ciphertext_proto__field_indices_by_name[] = {
  1,   /* field[1] = data */
  2,   /* field[2] = mac */
  0,   /* field[0] = pad */
};
static const ProtobufCIntRange hashed_el_gamal_ciphertext_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hashed_el_gamal_ciphertext_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HashedElGamalCiphertextProto",
  "HashedElGamalCiphertextProto",
  "HashedElGamalCiphertextProto",
  "",
  sizeof(HashedElGamalCiphertextProto),
  3,
  hashed_el_gamal_ciphertext_proto__field_descriptors,
  hashed_el_gamal_ciphertext_proto__field_indices_by_name,
  1,  hashed_el_gamal_ciphertext_proto__number_ranges,
  (ProtobufCMessageInit) hashed_el_gamal_ciphertext_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor election_partial_key_pair_backup_proto__field_descriptors[3] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionPartialKeyPairBackupProto, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiver",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionPartialKeyPairBackupProto, receiver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_coordinate",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ElectionPartialKeyPairBackupProto, encrypted_coordinate),
    &hashed_el_gamal_ciphertext_proto__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned election_partial_key_pair_backup_proto__field_indices_by_name[] = {
  2,   /* field[2] = encrypted_coordinate */
  1,   /* field[1] = receiver */
  0,   /* field[0] = sender */
};
static const ProtobufCIntRange election_partial_key_pair_backup_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor election_partial_key_pair_backup_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ElectionPartialKeyPairBackupProto",
  "ElectionPartialKeyPairBackupProto",
  "ElectionPartialKeyPairBackupProto",
  "",
  sizeof(ElectionPartialKeyPairBackupProto),
  3,
  election_partial_key_pair_backup_proto__field_descriptors,
  election_partial_key_pair_backup_proto__field_indices_by_name,
  1,  election_partial_key_pair_backup_proto__number_ranges,
  (ProtobufCMessageInit) election_partial_key_pair_backup_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor election_partial_key_verification_proto__field_descriptors[4] =
{
  {
    "sender",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionPartialKeyVerificationProto, sender),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiver",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionPartialKeyVerificationProto, receiver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "verifier",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(ElectionPartialKeyVerificationProto, verifier),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "verified",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(ElectionPartialKeyVerificationProto, verified),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned election_partial_key_verification_proto__field_indices_by_name[] = {
  1,   /* field[1] = receiver */
  0,   /* field[0] = sender */
  3,   /* field[3] = verified */
  2,   /* field[2] = verifier */
};
static const ProtobufCIntRange election_partial_key_verification_proto__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor election_partial_key_verification_proto__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ElectionPartialKeyVerificationProto",
  "ElectionPartialKeyVerificationProto",
  "ElectionPartialKeyVerificationProto",
  "",
  sizeof(ElectionPartialKeyVerificationProto),
  4,
  election_partial_key_verification_proto__field_descriptors,
  election_partial_key_verification_proto__field_indices_by_name,
  1,  election_partial_key_verification_proto__number_ranges,
  (ProtobufCMessageInit) election_partial_key_verification_proto__init,
  NULL,NULL,NULL    /* reserved[123] */
};
